env:
  browser: true
  node: true
  commonjs: true
  es6: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
overrides:
  files: ['**/*.ts', '**/*.tsx']
  parser: typescript-eslint-parser
  rules:
    no-undef: off
    no-unused-vars: off
